### ISSUE TITLE
two new papers for iccv2021

### ISSUE THREAD

**Issue by jiequancui** [extreme-assistant/ICCV2021-Paper-Code-Interpretation#18]
(1) Parametric Contrastive Learning
Jiequan Cui, Zhisheng Zhong, Shu Liu, Bei Yu, Jiaya Jia
paper: https://arxiv.org/abs/2107.12028
code: https://github.com/jiequancui/Parametric-Contrastive-Learning
Image classification, contrastive learning, imbalanced learning

(2) Learnable Boundary Guided Adversarial Training
Jiequan Cui, Shu Liu, Liwei Wang, Jiaya Jia
paper: https://arxiv.org/abs/2011.11164
code: https://github.com/jiequancui/LBGAT
Adversarial defense, Image classification

**Comment by extreme-assistant** [comment]
OK. 
Congratulations!

**Comment by jiequancui** [comment]
Big thanks
